[project]
name = "stock-screener-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "langchain>=0.3.27",
    "langgraph>=0.6.6",
]
